---
dependencies: []
galaxy_info:
  role_name: sizeup
  author: Taylor Kimball
  description: The Missing Window Manager
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - macos
    - sizeup
...
