---
dependencies: []
galaxy_info:
  role_name: proton_vpn
  author: Taylor Kimball
  description: VPN client focusing on security
  license: GPL-3.0-or-later
  min_ansible_version: 2.14.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - macos
    - proton
    - vpn
...
