---
dependencies: []
galaxy_info:
  role_name: textual
  author: Taylor Kimball
  description: Textual IRC Client
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - macos
    - textual
...
