---
dependencies: []
galaxy_info:
  role_name: adguard
  author: Taylor Kimball
  description: The world's most advanced ad blocker
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - adguard
    - macos
...
