---
dependencies: []
galaxy_info:
  role_name: rectangle
  author: Taylor Kimball
  description: Rectangle is a window management app based on Spectacle, written in Swift
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - macos
    - rectangle
...
