---
dependencies: []
galaxy_info:
  role_name: shell_proxy
  author: Taylor Kimball
  description: Configure proxies via command line
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - macos
    - proxy
    - shell
...
