---
homebrew_casks: []
homebrew_packages: []
homebrew_path: null
homebrew_sudo_password: null
homebrew_taps: []
homebrew_update: false
homebrew_upgrade: false
homebrew_upgrade_greedy: false
homebrew_upgrade_options: []
...
