---
dependencies: []
galaxy_info:
  role_name: irssi
  author: Taylor Kimball
  description: Your text mode chatting application since 1999
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - irssi
    - macos
...
