---
dependencies: []
galaxy_info:
  role_name: hermes
  author: Taylor Kimball
  description: Pandora Client
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - hermes
    - macos
...
