---
dependencies: []
galaxy_info:
  role_name: liquidprompt
  author: Taylor Kimball
  description: An adaptive prompt for bash and zsh
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - liquidprompt
    - macos
...
